---
- hosts: all
  remote_user: root
  tasks:
    - name: Copy config file
      copy:
        src: config/trackdirect
        dest: /opt/
        owner: root
        group: root
        mode: '0644'

- hosts: swarm-manager
  remote_user: root
  tasks:
    - name: Copy stack file
      copy:
        src: stacks/trackdirect.yml
        dest: /opt/trackdirect.yml
        owner: root
        group: root
        mode: '0644'

    - name: Deploy stack
      docker_stack:
        name: trackdirect
        prune: yes
        compose:
          - /opt/trackdirect.yml
      run_once: yes
