---
- hosts: swarm-manager
  remote_user: root
  tasks:
    - name: Copy stack file
      template:
        src: stacks/traefik.yml
        dest: /opt/traefik.yml
        mode: 0444
      vars:
        HASHED_PASSWORD: "{{ lookup('env', 'HASHED_PASSWORD') }}"
        EXTERNAL_IP: "{{ lookup('env', 'EXTERNAL_IP') }}"
      register: traefic_stack_file

    - name: Copy config file
      copy:
        src: config/traefik
        dest: /etc/
        owner: root
        group: root
        mode: '0644'
      register: traefic_config_file

    - name: Deploy stack
      docker_stack:
        name: traefik
        prune: yes
        compose:
          - /opt/traefik.yml
      run_once: yes
      when: traefic_stack_file.changed or traefic_config_file.changed

    - name: Copy stack file
      template:
        src: stacks/registry.yml
        dest: /opt/registry.yml
        mode: 0444
      register: registry_stack_file

    - name: Deploy stack
      docker_stack:
        name: registry
        prune: yes
        compose:
          - /opt/registry.yml
      run_once: yes
      when: registry_stack_file.changed
