version: "3.9"

services:
  aprsc:
    image: peterus/aprsc:latest
    volumes:
      - /opt/trackdirect/aprsc_aprs.conf:/opt/aprsc/etc/aprsc.conf
    ports:
      - "10152:10152"
      - "14580:14580"
      - "10155:10155"
      - "14501:14501"
    networks:
      - traefik_public
      - private
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.aprsc.entrypoints=https
        - traefik.http.services.aprsc.loadbalancer.server.port=14501
        - traefik.http.routers.aprsc.rule=Host(`aprsc.test.aprs-map.info`)
      placement:
        constraints:
          - node.role==worker

  collector:
    image: peterus/trackdirect-python:latest
    volumes:
      - /opt/trackdirect/trackdirect.ini:/root/trackdirect/config/trackdirect.ini
    command: /root/trackdirect/server/scripts/collector.sh trackdirect.ini 0
    networks:
      - private
    deploy:
      placement:
        constraints:
          - node.role==worker

  websocket:
    image: peterus/trackdirect-python:latest
    volumes:
      - /opt/trackdirect/trackdirect.ini:/root/trackdirect/config/trackdirect.ini
    command: /root/trackdirect/server/scripts/wsserver.sh trackdirect.ini
    networks:
      - private
      - traefik_public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.websocket.rule=Host(`websocket.test.aprs-map.info`)
        - traefik.http.routers.websocket.entrypoints=https
        - traefik.http.services.websocket.loadbalancer.server.port=9000
      placement:
        constraints:
          - node.role==worker

  web:
    image: peterus/trackdirect-apache:latest
    volumes:
      - /opt/trackdirect/trackdirect.ini:/root/trackdirect/config/trackdirect.ini
    networks:
      - private
      - traefik_public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.aprs_map.rule=Host(`test.aprs-map.info`)
        - traefik.http.routers.aprs_map.entrypoints=https
        - traefik.http.services.aprs_map.loadbalancer.server.port=80
      placement:
        constraints:
          - node.role==worker

  db:
    image: peterus/trackdirect-db:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: foobar
      POSTGRES_DB: trackdirect
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - private
    deploy:
      placement:
        constraints:
          - node.role==worker

#  remover:
#    image: peterus/trackdirect-python:latest
#    volumes:
#      - /opt/trackdirect/trackdirect.ini:/root/trackdirect/config/trackdirect.ini
#    command: /root/trackdirect/server/scripts/remover.sh trackdirect.ini
#    networks:
#      - private
#    deploy:
#      labels:
#        - swarm.cronjob.enable=true
#        - swarm.cronjob.schedule=5 * * * *
#        - swarm.cronjob.skip-running=true
#      replicas: 0
#      restart_policy:
#        condition: none
#      placement:
#        constraints:
#          - node.role==worker

networks:
  traefik_public:
    external: true
  private:

volumes:
  db:
    driver: hetzner
    driver_opts:
      size: '50'
      fstype: xfs
