version: "3.9"

services:
  aprsc:
    image: registry.test.aprs-map.info/aprsc:latest
    volumes:
      - /opt/trackdirect/aprsc_aprs.conf:/opt/aprsc/etc/aprsc.conf
    networks:
      - private
      - traefik_public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.aprsc.rule=Host(`aprs-is.test.aprs-map.info`)
        - traefik.http.routers.aprsc.entrypoints=https
        - traefik.http.services.aprsc.loadbalancer.server.port=14501
      placement:
        constraints:
          - node.labels.swarm_node == worker

  collector:
    image: registry.test.aprs-map.info/trackdirect-python:latest
    volumes:
      - /opt/trackdirect/trackdirect.ini:/root/trackdirect/config/trackdirect.ini
    command: /root/trackdirect/server/scripts/collector.sh trackdirect.ini 0
    networks:
      - private
    deploy:
      placement:
        constraints:
          - node.labels.swarm_node == worker

  websocket:
    image: registry.test.aprs-map.info/trackdirect-python:latest
    volumes:
      - /opt/trackdirect/trackdirect.ini:/root/trackdirect/config/trackdirect.ini
    command: /root/trackdirect/server/scripts/wsserver.sh trackdirect.ini
    networks:
      - private
      - traefik_public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.websocket.rule=Host(`websocket.test.aprs-map.info`)
        - traefik.http.routers.websocket.entrypoints=https
        - traefik.http.services.websocket.loadbalancer.server.port=9000
      placement:
        constraints:
          - node.labels.swarm_node == worker

  web:
    image: registry.test.aprs-map.info/trackdirect-apache:latest
    volumes:
      - /opt/trackdirect/trackdirect.ini:/root/trackdirect/config/trackdirect.ini
    networks:
      - private
      - traefik_public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.aprs_map.rule=Host(`test.aprs-map.info`)
        - traefik.http.routers.aprs_map.entrypoints=https
        - traefik.http.services.aprs_map.loadbalancer.server.port=80
      placement:
        constraints:
          - node.labels.swarm_node == worker

  db:
    image: registry.test.aprs-map.info/db:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: foobar
      POSTGRES_DB: trackdirect
    volumes:
      - db:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - node.labels.swarm_node == worker

  remover:
    image: registry.test.aprs-map.info/trackdirect-python:latest
    volumes:
      - /opt/trackdirect/trackdirect.ini:/root/trackdirect/config/trackdirect.ini
    command: /root/trackdirect/server/scripts/remover.sh trackdirect.ini
    deploy:
      labels:
        - swarm.cronjob.enable=true
        - swarm.cronjob.schedule=5 * * * *
        - swarm.cronjob.skip-running=true
      replicas: 0
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.swarm_node == worker


networks:
  private:
  traefik_public:
    external: true


volumes:
  db:
    driver: hetzner
