name: deploy

on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    name: Deploy to Hetzner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Terraform Init
        run: terraform init
      - name: Terraform Apply
        run: terraform apply
