name: deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy to Hetzner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Terraform Init
        run: cd hetzner && terraform init
      - name: Terraform Apply
        env:
          TF_VAR_HCLOUD_TOKEN: ${{ secrets.TF_VAR_HCLOUD_TOKEN }}
        run: cd hetzner && terraform apply -auto-approve
